[book]
authors = ["CDL Team"]
language = "en"
multilingual = false
src = "docs"
title = "The Common Data Layer"

[build]
build-dir = "target/book"

[output.html]
git-repository-url = "https://github.com/epiphany-platform/CommonDataLayer"

[output.linkcheck]
warning-policy = "error"

[preprocessor.plantuml]
