@startuml
skinparam backgroundColor #FEFEFE
skinparam transparent false

actor "User (REST)" as REST
participant "Query Router" as QR
database "Schema Registry" as SR
database "Query Service" as QS

REST -> QR: Query for data
QR -> SR: Query for schema_id
SR -> QR: Retrieve associated query_service, data_type
QR -> QS: Query for data
QS -> QR: Retrieve document
QR -> REST: Retrieve document
@enduml
