---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-sled-db
  labels:
    app: {{ .Release.Name }}-sled-db
spec:
  serviceName: {{ .Release.Name }}-sled-db
  replicas: {{ .Values.replicaDbCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sled-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sled-db
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-sled-db
        image: "{{ .Values.global.imageRepositoryPath }}cdl-document-storage:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/document-storage"]
        env:
        - name: RUST_LOG
          value: "info,document-storage=debug"
        ports:
        - containerPort: 51805
        volumeMounts:
        - mountPath: "/var/data/datastore_rs"
          name: {{ .Release.Name }}-pv-sled
      imagePullSecrets:
      - name: {{ .Values.global.cdlImagePullSecrets }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-pv-sled
    spec:
      storageClassName: {{ .Values.storageClass }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.maxDbSize }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sled-command-service
  labels:
    app: {{ .Release.Name }}-sled-command-service
    repository.type: document
    repository.name: sled
spec:
  replicas: {{ .Values.replicaCommandCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sled-command-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sled-command-service
        repository.type: document
        repository.name: sled
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-sled-command-service
        image: "{{ .Values.global.imageRepositoryPath }}cdl-command-service:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/command-service","sleigh"]
        env:
        - name: QUEUE_CONNECTION_STRING
          value: {{ .Values.global.rabbitConnectionString }}
        - name: QUEUE_CONSUMER_TAG
          value: "cdl-postgres-command-service"
        - name: ORDERED_QUEUE_NAMES
          value: {{ .Values.inputTopic }}
        - name: SLEIGH_OUTPUT_ADDR
          value: "http://{{ .Release.Name }}-sled-db:58102"
        - name: REPORT_BROKER
          value: {{ .Values.global.kafkaBrokers }}
        - name: REPORT_TOPIC
          value: {{ .Values.global.reportTopic }}
        - name: INGESTION_METHOD
          value: {{ .Values.ingestionMethod }}
        - name: RUST_LOG
          value: "info,command_service=debug"
        ports:
        - containerPort: 51805
  # TODO: Probes
      imagePullSecrets:
      - name: {{ .Values.global.cdlImagePullSecrets }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sled-db
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-sled-db
  ports:
    - port: 58102
      targetPort: 58102

