@startuml
skinparam linetype polyline
skinparam backgroundColor #FEFEFE
skinparam transparent false

interface "Configuration Layer" as ConfOut
interface "Configuration Layer" as ConfAPI
interface "Ingestion Layer" as DRAPI
interface "Materialization Layer" as MatAPI

cloud {
  [External System]
}

frame "Management Layer" {
    [CLI]
    [Admin Web Panel]
}


frame "Ingestion Layer" {
  [Data Router] -left--. [Configuration Layer]
}

frame "Configuration Layer" {
  [Schema Registry]
  [Leader Elector] -left--. [Schema Registry]
  [Edge Registry]
}

frame "Storage Layer" {
    node "Repository Doc" {
      [Command Service Doc]

      database "Postgres" {
        [Document Data]
      }

      [DB Shrinker Storage]

      [Query Service Doc]
    }

    node "Repository TS" {
      [Command Service TS]

      database "Victoria Metrics" {
        [Timeseries Data]
      }

      [Query Service TS]
    }


    () "any number of repositories (Document/Timeseries/Blob)" as ANY
}

frame "Materialization Layer" {
    [Partial Update Engine] -down-> [Object Builder]: MQ
    [Object Builder] -down--. ConfOut
    node "Postgres Repository" {
        [Materializer Postgres]

        database "Postgres" as Postgres2 {
            [Materialized Views]
        }
    }
    [On Demand Materializer] -up--. [Object Builder]
}

frame "Retrieval Layer" {
  [Query Router] -right-. ConfOut
}

cloud {
  actor User
}

[Admin Web Panel] -down-> [API] : GraphQL
[External System] -down-> [Data Router] : MQ
[Data Router] -down--> [Command Service Doc] : MQ
[Data Router] -down-> [Command Service TS] : MQ
[Data Router] -down-> ANY : MQ
[Command Service Doc] -down-> [Document Data] : SQL
[Command Service TS] -down-> [Timeseries Data] : REST
[Command Service Doc] -down-> [Partial Update Engine]: MQ
[Command Service TS] -down-> [Partial Update Engine]: MQ
[Materializer Postgres] -down-> [Materialized Views] : SQL
ANY -down-> [Partial Update Engine]: MQ
[DB Shrinker Storage] -down-> [Document Data] : SQL
[Query Service Doc] -up-> [Document Data] : SQL
[Query Service TS] -up-> [Timeseries Data] : REST
[Query Router] -up--> [Query Service Doc] : gRPC
[Query Router] -up-> [Query Service TS] : gRPC
[Query Router] -up-> ANY : gRPC
[Object Builder] -up-> [Query Service Doc]: gRPC
[Object Builder] -up-> [Query Service TS]: gRPC
[Object Builder] -up-> ANY : gRPC
[Object Builder] -up-> [Materializer Postgres]: gRPC
[API] -up--. MatAPI
[API] --up--. ConfAPI
[API] -up--. DRAPI
User -up-> [Query Router] : REST
User -up-> [On Demand Materializer]: gRPC
User -up-> [Admin Web Panel]: HTTP
User -up-> [Materialized Views] : SQL
@enduml
