@startuml
skinparam linetype polyline
skinparam backgroundColor #FEFEFE
skinparam transparent false

interface "Configuration Layer" as ConfIn
interface "Configuration Layer" as ConfOut

cloud {
  [External System]
}

frame "Management Layer" {
    [CLI]
    [Admin Web Panel]
}

[API] <-up-> [Configuration Layer]

frame "Ingestion Layer" {
  API -left--> [Data Router]
  [Data Router] -left--. ConfIn
}

frame "Configuration Layer" {
  [Schema Registry]
  [Leader Elector] -left--. [Schema Registry]
  [Edge Registry]
}

frame "Storage Layer" {
    node "Repository Doc" {
      [Command Service Doc]

      database "Postgres" {
        [Document Data]
      }

      [DB Shrinker Storage]

      [Query Service Doc]
    }

    node "Repository TS" {
      [Command Service TS]

      database "Victoria Metrics" {
        [Timeseries Data]
      }

      [Query Service TS]
    }


    () "any number of repositories (Document/Timeseries/Blob)" as ANY
}

frame "Retrieval Layer" {
  [Query Router] -right-. ConfOut
}

cloud {
  actor User
}

[Admin Web Panel] -down-> [API] : GraphQL
[External System] -down-> [Data Router] : MQ
[Data Router] -down--> [Command Service Doc] : MQ
[Data Router] -down-> [Command Service TS] : MQ
[Data Router] -down-> ANY : MQ
[Command Service Doc] -down-> [Document Data] : SQL
[Command Service TS] -down-> [Timeseries Data] : REST
[DB Shrinker Storage] -down-> [Document Data] : SQL
[Query Service Doc] -up-> [Document Data] : SQL
[Query Service TS] -up-> [Timeseries Data] : REST
[Query Router] -up--> [Query Service Doc] : gRPC
[Query Router] -up-> [Query Service TS] : gRPC
[Query Router] -up-> ANY : gRPC
User -up-> [Query Router] : REST
@enduml
