apiVersion: v1
kind: Pod
metadata:
  name: data-injector
spec:
  restartPolicy: Never
  containers:
    - image: cdl-upload-to-rabbitmq
      imagePullPolicy: IfNotPresent
      name: data-injector
      command:
        [
          "/usr/src/cdl/upload-to-rabbitmq",
          "-a",
          "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f",
          "-c",
          "500",
          "-e",
          "",
          "-k",
          "cdl.data.input",
          "-s",
          "e8991bb3-12d6-11eb-8000-000000000000",
        ]
      ports:
        - containerPort: 8080
          protocol: TCP
  imagePullSecrets:
    - name: services
