@startuml
participant MQ
participant "Data Router" as DR
database "Schema Registry" as SR

MQ -> DR: Message from external system
DR -> DR: Attach timestamp to message
DR -> SR: Query for schema_id
SR -> DR: Retrieve associated MQ topic
DR -> MQ: Re-route message to corresponding topic
@enduml
