// CAUTION: This module was automatically generated by `cargo xtask codegen`. Do not modify it.

pub mod common;
pub mod edge_registry;
pub mod generic_rpc;
pub mod materializer_general;
pub mod materializer_ondemand;
pub mod object_builder;
pub mod query_service;
pub mod query_service_ts;
pub mod schema_registry;
